name: Unit Test
on:
  push:
    branches:
      - refactor-knowledge-model
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-deduction-common
  PJ_BRANCH: refactor-knowledge-model
  PJ_VERSION: 0.5-SNAPSHOT
jobs:
  unit-test_toposoid-deduction-common:
    runs-on: self-hosted
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker-compose -f docker-compose-workflow.yml up -d toposoid-deduction-common
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"
            docker-compose -f docker-compose-workflow.yml up -d neo4j
            docker-compose -f docker-compose-workflow.yml up -d scala-data-accessor-neo4j-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-japanese-web
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*JapaneseTest'"
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-sentence-parser-japanese-web
            docker rmi --force toposoid/toposoid-sentence-parser-japanese-web:${{ env.PJ_VERSION }}-workflow
            docker rmi --force toposoid/toposoid-common-nlp-japanese-web:${{ env.PJ_VERSION }}-workflow
            docker system prune -f
            docker volume prune -f
            docker-compose -f docker-compose-workflow.yml up -d corenlp
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-english-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-english-web
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*EnglishTest'"

